Models/BaseEntity.cs
namespace DojoLeague.Models
{
    public abstract class BaseEntity {}
}

Models/Dojo.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace DojoLeague.Models 
{
    public class Dojo : BaseEntity
    {
       public Dojo() 
       {
           ninjas = new List<Ninja>();
       }
       public int ID {get; set;}
       [Required(ErrorMessage = "Name is required")]
       public string DojoName {get; set;}
       [Required(ErrorMessage = "Location is required")]
       public string DojoLocation {get; set;}
       [Required(ErrorMessage = "Additional Dojo informaiton is required")]
       public string DojoDescription {get; set;}
       public DateTime CreatedAt {get; set;}
       public DateTime UpdatedAt {get; set;}
       public ICollection<Ninja> ninjas {get; set;}
    }
}

Models/ErrorViewModel.cs
using System;

namespace DojoLeague.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Ninja.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace DojoLeague.Models
{
    public class Ninja : BaseEntity 
    {
        public int ID {get; set;}
        public int? DojoID {get; set;}
        [Required(ErrorMessage = "Name is required")]
        public string NinjaName {get; set;}
        public int NinjaLevel {get; set;}
        public string NinjaDescription {get; set;}
        public DateTime CreatedAt {get; set;}
        public DateTime UpdatedAt {get; set;}
        public Dojo dojos {get; set;}
    }
}

Controllers/DojoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DojoLeague.Models;
using DojoLeague.Factories;

namespace DojoLeague.Controllers
{
    public class DojoController : Controller
    {
        private readonly DojoFactory _dojoFactory;
        public DojoController(DojoFactory dojoFactory)
        {
            _dojoFactory = dojoFactory;
        }
        // GET: /dojos
        [HttpGet("dojos")]
        public IActionResult Main_Dojo()
        {
            ViewBag.allDojos = _dojoFactory.GetAllDojos();
            return View();
        }
        // POST: /dojos/new
        [HttpPost("dojos/new")]
        public IActionResult AddDojo(Dojo dojo)
        {
            if(ModelState.IsValid)
            {
                _dojoFactory.CreateDojo(dojo);
                return RedirectToAction("Main_Dojo");
            }
            ViewBag.allDojos = _dojoFactory.GetAllDojos();
            return View("Main_Dojo");
        }
        // GET: dojos/id
        [HttpGet("dojos/{id}")]
        public IActionResult Dojo(int id)
        {
            ViewBag.dojo = _dojoFactory.GetDojo(id);
            ViewBag.rogueNinjas = _dojoFactory.GetRogueNinjas();
            return View();
        }
        // GET: dojos/id/banish/ninjas/id/update
        [HttpGet("dojos/{dojoID}/banish/ninjas/{ninjaID}/update")]
        public IActionResult DojoBanishment(int dojoID, int ninjaID)
        {
            _dojoFactory.BanishNinja(ninjaID);
            return RedirectToAction("Dojo", new{id = dojoID});
        }
        // GET: dojos/id/recruit/ninjas/id/update
        [HttpGet("dojos/{dojoID}/recruit/ninjas/{ninjaID}/update")]
        public IActionResult DojoRecruitement(int dojoID, int ninjaID)
        {
            _dojoFactory.RecruitNinja(dojoID, ninjaID);
            return RedirectToAction("Dojo", new{id = dojoID});  
        }
    }
}

Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DojoLeague.Models;
using DojoLeague.Factories;

namespace DojoLeague
{
    public class MainController : Controller 
    {
        [HttpGet("")]
        public IActionResult Main()
        {    
            return View();
        }
        
    }
}

Controllers/NinjaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DojoLeague.Models;
using DojoLeague.Factories;

namespace DojoLeague.Controllers
{
    public class NinjaController : Controller
    {
        private readonly NinjaFactory _ninjaFactory;
        public NinjaController(NinjaFactory ninjaFactory)
        {
            _ninjaFactory = ninjaFactory;
        }
        // GET: /ninjas
        [HttpGet("ninjas")]
        public IActionResult Main_Ninja()
        {
            ViewBag.allNinjas = _ninjaFactory.GetAllNinjas();
            ViewBag.allDojos = _ninjaFactory.GetAllDojos(); // Will be used for registering ninja to dojo
            return View();
        }
        // POST: /ninjas/new
        [HttpPost("ninjas/new")]
        public IActionResult AddNinja(Ninja ninja)
        {
            if(ModelState.IsValid)
            {
                _ninjaFactory.CreateNinja(ninja);
                return RedirectToAction("Main_Ninja");
            }
            ViewBag.allNinjas = _ninjaFactory.GetAllNinjas();
            ViewBag.allDojos = _ninjaFactory.GetAllDojos(); // Will be used for registering ninja to dojo
            return View("Main_Ninja");
        }
        // GET: /ninja/id
        [HttpGet("ninjas/{id}")]
        public IActionResult Ninja(int id)
        {
            ViewBag.ninja = _ninjaFactory.GetNinja(id);
            return View();
        }
    }
}

Views/Dojo/dojo.cshtml
<h1>@ViewBag.dojo.DojoName</h1>
<p>Dojo Location: @ViewBag.dojo.DojoLocation</p>
<p>Information: @ViewBag.dojo.DojoDescription </p>
<div class="ninjas_div">
    <h2>Current Members</h2>
    <table>
        <thead>
            <tr>
                <th>Ninja</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var ninja in ViewBag.dojo.ninjas)
            {
                <tr>
                    <td><a href="/ninjas/@ninja.ID">@ninja.NinjaName</a></td>
                    <td><a href="/dojos/@ViewBag.dojo.ID/banish/ninjas/@ninja.ID/update">Banish</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="ninjas_div">
    <h2>Rogue Ninjas</h2>
    <table>
        <thead>
            <tr>
                <th>Ninja</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var rogue in ViewBag.rogueNinjas)
            {
                <tr>
                    <td><a href="/ninjas/@rogue.ID">@rogue.NinjaName</a></td>
                    <td><a href="/dojos/@ViewBag.dojo.ID/recruit/ninjas/@rogue.ID/update">Recruit</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>
<a style="display: block;" href="/dojos">Return to Dojos</a>
<a style="display: block;" href="/">Go Home</a>

Views/Dojo/main_dojo.cshtml
@model Dojo
<div class="info_div">
    <h1>Dojos</h1>
    <table>
        <thead>
            <tr>
                <th>Dojo Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var dojo in ViewBag.allDojos)
            {
                <tr>
                    <td><a href="/dojos/@dojo.ID">@dojo.DojoName</a></td>
                </tr>
            }
        </tbody>
    </table>
</div><div class="form_div">
    <h1>Register Dojo</h1>
    <div asp-validation-summary="All"></div>
    <form asp-action="AddDojo" asp-controller="Dojo" method="post">
        <label style="display: block;" asp-for="DojoName">Dojo Name</label>
        <input asp-for="DojoName">
        <label style="display: block;" asp-for="DojoLocation">Dojo Location</label>
        <input asp-for="DojoLocation">
        <label style="display: block;" asp-for="DojoDescription">Additional Dojo Information</label>
        <textarea asp-for="DojoDescription" cols="30" rows="10"></textarea>
        <input type="submit" value="Add">
    </form>
    <a style="display: block;" href="/ninjas">Go to Ninjas</a>
    <a style="display: block;" href="/">Go Home</a>
</div>

Views/Main/main.cshtml
<h1>Dojo League</h1>
<a href="/ninjas">Ninjas</a> | <a href="/dojos">Dojos</a>

Views/Ninja/main_ninja.cshtml
@model Ninja
<div class="info_div">
    <h1>Registered Ninjas</h1>
    <table>
        <thead>
            <tr>
                <th>Ninja Name</th>
                <th>Home Dojo</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var ninja in ViewBag.allNinjas)
            {
                <tr>
                    <td><a href="/ninjas/@ninja.ID">@ninja.NinjaName</a></td>
                    @if(@ninja.dojos != null)
                    {
                        <td><a href="/dojos/@ninja.dojos.ID">@ninja.dojos.DojoName</a></td>
                    }
                    else
                    {
                        <td>Rogue</td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div><div class="form_div">
    <h1>Register a Ninja</h1>
    <div asp-validation-summary="All"></div>
    <form asp-action="AddNinja" asp-controller="Ninja" method="post">
        <label style="display: block;" asp-for="NinjaName">Ninja Name</label>
        <input asp-for="NinjaName">
        <label style="display: block;" asp-for="NinjaLevel">Ninja Level (1-10)</label>
        <select asp-for="NinjaLevel">
            @for(int i =1; i < 11; i++)
            {
                <option>@i</option>
            }
        </select>
        <label style="display: block;" asp-for="DojoID">Assigned Dojo?</label>
        <select asp-for="DojoID">
            <option value="">Rogue</option>
            @foreach(var dojo in ViewBag.allDojos)
            {
                <option value="@dojo.ID">@dojo.DojoName</option>
            }
        </select>
        <label style="display: block;" asp-for="NinjaDescription">Optional Description</label>
        <textarea asp-for="NinjaDescription" cols="30" rows="10"></textarea>
        <input style="display: block;" type="submit" value="Add">
    </form>
    <a style="display: block;" href="/dojos">Go to Dojos</a>
    <a style="display: block;" href="/">Go Home</a>
</div>

Views/Ninja/ninja.cshtml
@foreach(var ninja in ViewBag.ninja)
{
    <h1>Name: @ninja.NinjaName </h1>
    <p>Ninja Level: @ninja.NinjaLevel </p>
    @if(@ninja.NinjaDescription != null)
    {
        <p>Description: @ninja.NinjaDescription</p>
    }
    @if(@ninja.dojos == null)
    {
        <p>Current Dojo: Rogue </p>
    }
    else 
    {
        <p>Current Dojo: <a href="/dojos/@ninja.dojos.ID">@ninja.dojos.DojoName</a></p>
    }
    <a style="display: block;" href="/ninjas">Return to Ninjas</a>
    <a style="display: block;" href="/">Go Home</a>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DojoLeague</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DojoLeague</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - DojoLeague</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>